CREATE TABLE STUDENT(
  CUS_ID NUMBER,
  F_NAME VARCHAR2(20),
  L _NAME VARCHAR2(20),
  DEPT varchar2(10),
  SALARY NUMBER,
  CITY varchar2(10)
);

INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(1,'ALMAS','HOSSAIN','ICT',2000,'KUSHTIA');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(2,'MUJAHID','HOSSAIN','ICT',200000,'N-GONG');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(3,'kamrul','HOSSAIN','ICT',200000,'l-GONG');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(4,'mohibur','HOSSAIN','cse',200000, 'k-GONG');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES (5,'UTSHO','HOSSAIN','BANGLA',100000,'DHAKA');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES (6,'SAMAR','ICT','MATH',50000,'SHAVAR');

SELECT * FROM STUDENT ORDER BY DEPT DESC;
SELECT * FROM STUDENT WHERE SALARY > 200000;
UPDATE STUDENT SET SALARY= 2000000 WHERE CUS_ID=1;
SELECT * FROM STUDENT;
DELETE FROM STUDENT WHERE CUS_ID=6;

UPDATE STUDENT SET F_NAME= 'ASHRAFUL',L_NAME='ALAM' WHERE CUS_ID=5;

ALTER TABLE STUDENT ADD ZIP_CODE NUMBER;
UPDATE STUDENT SET ZIP_CODE=786 WHERE CUS_ID=4;
UPDATE STUDENT SET ZIP_CODE=890 WHERE CUS_ID=5;
UPDATE STUDENT SET ZIP_CODE=999 WHERE CUS_ID=6;

ALTER TABLE STUDENT ADD SEX VARCHAR2(10); 
ALTER TABLE STUDENT  DROP COLUMN SEX; 

SELECT ZIP_CODE CODE FROM STUDENT;
SELECT F_NAME ||' '|| L_NAME AS NAME FROM STUDENT;

SELECT &ENTER_COLUMN_NAME FROM STUDENT 
WHERE &PUT_CONDITION;

SELECT DISTINCT SALARY, F_NAME AS NAME FROM STUDENT;
SELECT SALARY,SALARY*1.5 AS BONUSE FROM STUDENT;
