SET SERVEROUTPUT ON;
------DECLARE
----- V_SOL VARCHAR2(10);
------BEGIN
----  V_SOL:='ICT';
----  DBMS_OUTPUT.PUT_LINE(V_SOL);
------END;
CREATE TABLE EMPLOYEES(
  EMPLOYEES_ID NUMBER(10),
  NAME VARCHAR2(20 BYTE),
  DEPARTMENT VARCHAR2(10BYTE)
);
ALTER TABLE EMPLOYEES ADD SALARY NUMBER(10);
DESC EMPLOYEES;
INSERT INTO EMPLOYEES VALUES(100,'ALMAS','ICT',100000);
INSERT INTO EMPLOYEES VALUES(101,'HOSSAIN','EEE',50000);
INSERT INTO EMPLOYEES VALUES(102,'ANATR','CSE',30000);

SELECT * FROM EMPLOYEES;
DECLARE
  V_SALARY NUMBER(10);
BEGIN
  SELECT SALARY INTO V_SALARY FROM EMPLOYEES
  WHERE EMPLOYEES_ID=102;
  DBMS_OUTPUT.PUT_LINE(V_SALARY);
END;
/
DECLARE 
  V_SALARY NUMBER(10);
  V_NAME VARCHAR2(20 BYTE);
BEGIN
  SELECT NAME, SALARY INTO V_NAME,V_SALARY FROM EMPLOYEES
  WHERE EMPLOYEES_ID=100;
  DBMS_OUTPUT.PUT_LINE(V_NAME||' '|| 'AND HIS SALARY IS' ||' '|| V_SALARY);
END;
/
DECLARE
V_F_NAME EMPLOYEES.NAME%TYPE;
BEGIN
  SELECT NAME INTO V_F_NAME FROM EMPLOYEES
  WHERE EMPLOYEES_ID=100;
  DBMS_OUTPUT.PUT_LINE('THE NAME OF THE BOSS IS'||' '||V_F_NAME);
  DBMS_OUTPUT.PUT_LINE('BOSS IS ALMAS');
END;
/
ALTER TABLE EMPLOYEES MODIFY NAME CHAR(12);
SET SERVEROUTPUT ON;
DECLARE
  KOP CONSTANT NUMBER(7,6) NOT NULL DEFAULT 3.1416;
BEGIN
  DBMS_OUTPUT.PUT_LINE(KOP);
END;
 /
SET SERVEROUTPUT ON;
DECLARE
  KOP CONSTANT NUMBER(7,6) NOT NULL := 3.1416;
BEGIN
  DBMS_OUTPUT.PUT_LINE(KOP);
END;

 
 
 
 
 
 
 
 
 
 
 