CREATE TABLE JKL(
  F_NAME VARCHAR2(30)
);

SET SERVEROUTPUT ON;
DECLARE
  TYPE CUR IS TABLE OF NUMBER;
  V_VAR CUR:= CUR(1,34,23,545,234,1223,454,342,2234,3423,2342);
  
  TYPE IN_X IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER;
  V_VAR2 IN_X;
  V_COUNT NUMBER;
  
BEGIN
  V_VAR2 (1) := 2;
  V_VAR2 (2) := 4;
  V_VAR2 (7) := 8;
  V_VAR2 (5) := 9;

  FORALL ID_X IN VALUES OF V_VAR2
    INSERT INTO JKL(F_NAME) VALUES(V_VAR(ID_X));
  
    SELECT COUNT(*) INTO V_COUNT FROM JKL;
     DBMS_OUTPUT.PUT_LINE(V_COUNT);
END;
/
SELECT * FROM JKL;