CREATE TABLE AL(
  TUT_TUT NUMBER(10)
);
DESC AL;
SET SERVEROUTPUT ON;
DECLARE
 TYPE A_ARRAY IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
 V_VAR1 A_ARRAY;
 V_COUNT NUMBER;
 
BEGIN
  
  FOR ID_X IN 1..10
   LOOP
    V_VAR1(ID_X):= 9*ID_X;
   END LOOP;
  
 FORALL ID_F IN 1..10
    INSERT INTO AL(TUT_TUT)
      VALUES(V_VAR1(ID_F));
  SELECT COUNT(*) INTO V_COUNT FROM AL;
  DBMS_OUTPUT.PUT_LINE('THE INSERTED ROW ARE '|| V_COUNT);
END;
/