CREATE TABLE AL(
  TUT_TUT NUMBER(10)
);
DESC AL;
DECLARE
 TYPE A_ARRAY IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
 V_VAR1 A_ARRAY;
 V_COUNT NUMBER;
 
BEGIN
  
  FOR ID_X IN 1..10
   LOOP
    