CREATE TABLE ALMAS(
  F_NAME VARCHAR2(30)
);
CREATE TABLE AIM(
  AIM_NAME VARCHAR2(30)
);
CREATE VIEW INSTADE_TRG AS 
SELECT F_NAME,AIM_NAME FROM ALMAS,AIM;

INSERT INTO INSTADE_TRG VALUES('ALMAS HOSSAIN','SOFTWARE ENGINEER');
INSERT INTO INSTADE_TRG VALUES('KAMRUL HASAN','FATRA');
-----TRIGGER CREATING-----
CREATE OR REPLACE TRIGGER INSTADEOF
INSTEAD OF INSERT ON INSTADE_TRG
FOR EACH ROW
BEGIN
  INSERT INTO ALMAS (F_NAME) VALUES(:NEW.F_NAME);
  INSERT INTO AIM (AIM_NAME) VALUES(:NEW.AIM_NAME);
END;
/
SELECT * FROM INSTADE_TRG;



------UPDATE PART--------
UPDATE INSTADE_TRG SET AIM_NAME= 'SOFTWARE ENGINEER' WHERE F_NAME = 'KAMRUL HASAN';

CREATE OR REPLACE TRIGGER INSTADE_UPDATE
INSTEAD OF UPDATE ON INSTADE_TRG
FOR EACH ROW
BEGIN
  UPDATE ALMAS SET F_NAME = :NEW.F_NAME WHERE F_NAME = :OLD.F_NAME;
  UPDATE AIM SET AIM_NAME = :NEW.AIM_NAME WHERE AIM_NAME = :OLD.AIM_NAME;
END;
/
SELECT * FROM INSTADE_TRG;
/
-------DELETE PART-------
CREATE OR REPLACE TRIGGER INSTADE_DELETE
INSTEAD OF DELETE ON INSTADE_TRG
FOR EACH ROW
DECLARE
BEGIN
  DELETE FROM ALMAS WHERE F_NAME = :OLD.F_NAME;
  DELETE FROM AIM WHERE AIM_NAME = :OLD.AIM_NAME;
END;
/
DELETE FROM INSTADE_TRG WHERE F_NAME='KAMRUL HASAN';














