SET SERVEROUTPUT ON;
  DECLARE
    V_VAR VARCHAR2(30);
    V_VAR1 VARCHAR2(200);  BEGIN
    V_VAR1 := 'CREATE TABLE KO('||
      'STU_NAME VARCHAR(30)'||
    ')';
  EXECUTE IMMEDIATE V_VAR1;
END;
ALTER TABLE KO MODIFY COLUMN STU_NAME VARCHAR2(30);
/

/
 DECLARE
    V_VAR1 VARCHAR2(300);
  BEGIN
    V_VAR1 := 'CREATE TABLE KU('||
      'STU_NAME VARCHAR2(30)'||
    ')';
  EXECUTE IMMEDIATE V_VAR1;
END;
/
DECLARE
  V_VAR3 VARCHAR2(300);
BEGIN
  V_VAR3 := 'INSERT INTO KU(STU_NAME) VALUES(:STU_NAM)';
  EXECUTE IMMEDIATE V_VAR3 USING 'ALMAS';
END;
/
SELECT * FROM KU;
/

-----USING MULTIPLE BIND VARIABLE IN NDS------

CREATE TABLE KL(
  F_NAME VARCHAR2(30),
  L_NAME VARCHAR2(30)
);
INSERT INTO KL VALUES('ALMAS','HOSSAIN');
INSERT INTO KL VALUES('ANTRA','BOSS');
SELECT * FROM KL;
SET SERVEROUTPUT ON;
DECLARE
  V_VAR VARCHAR2(303);
BEGIN
   V_VAR:= 'UPDATE KL SET F_NAME=:NEW_NAME
   WHERE L_NAME=:OLD_NAME';
   
   EXECUTE IMMEDIATE V_VAR USING 'ENGINEER','BOSS';
END;
/
SELECT * FROM KL;
/
DECLARE
  TYPE KHH IS TABLE OF VARCHAR2(30);
  V_VAR KHH;
  V_VAR1 VARCHAR2(30);
BEGIN
  V_VAR1:= 'SELECT F_NAME FROM KL';
  EXECUTE IMMEDIATE V_VAR1 BULK COLLECT INTO V_VAR;
  FOR ID_X IN V_VAR.FIRST..V_VAR.LAST
   LOOP
    DBMS_OUTPUT.PUT_LINE(ID_X|| ' ' || V_VAR(ID_X));
   END LOOP;
END;
/


















