CREATE TABLE JH(
  F_NAME VARCHAR2(10)
);

INSERT INTO JH(F_NAME) VALUES('ALMAS');
INSERT INTO JH(F_NAME) VALUES('HOSSAIN');
INSERT INTO JH(F_NAME) VALUES('ANTAR');
INSERT INTO JH(F_NAME) VALUES('BOSS');
SELECT * FROM JH;


SET SERVEROUTPUT ON;
  DECLARE
    V_VAR VARCHAR2(30);
    V_VAR1 NUMBER;
  BEGIN
    V_VAR := 'SELECT COUNT(*) FROM JH';
    EXECUTE IMMEDIATE V_VAR INTO V_VAR1;
    DBMS_OUTPUT.PUT_LINE('THE TOTTAL NUMBER IS '|| V_VAR1);
  END;
  /