SET SERVEROUTPUT ON;
DECLARE
  V_RECORD USERINFO%ROWTYPE;
BEGIN
  :ERC_MES := '';
  SELECT * INTO V_RECORD FROM USERINFO
  WHERE USERANAME = :CONTRL.USERNAE;
  :GLOBAL.USERNAM := V_RECORD.USERNAME;
  
  
  ---- IN THE FORM TRIGGER SECTION WE SET IT -----
  :USER := :GLOBAL.USERNAM;
  :SDATE := SYSDATE;
  
  
  IF V_RECORD.PASS = :CONTROL.PS THEN
      IF 
        V_RECORD.USER_TYPE = 'ADMIN' THEN
        OPEN_FORM('GIVE THE FORM PATH NAME');
      ELSIF 
        V_RECORD.USER_TYPE = 'OPERATOR' THEN
        OPEN_FORM('GIVE THE FORM PATH NAME');
      ELSIF 
        V_RECORD.USERTYPRE = 'AUDIT' THEN
        OPEN_FORM('GIVE THE FORM PATH NAME');
     END IF;
  ELSIF
     V_RECORD.PASS <> :CONTROL.PS THEN
      :ERC_MES := 'INVALID PASSWORD';
      MESSAGE('INVALID PASSWORD');
      MESSAGE('INVALID PASSWORD');
  ELSIF 
      V_RECIRD.PASS IS NULL THEN
      :ERC_MES := 'BOSS PLEASE BOSS ENTER THE PASSWORD FIRST';
      MESSAGE('BOSS PLEASE BOSS ENTER THE PASSWORD FIRST');
      MESSAGE('BOSS PLEASE BOSS ENTER THE PASSWORD FIRST');
  ELSIF
     :CONTROL.USERNAM IS NULL THEN
     :ERC_MES := 'BOSS PLEASE ENTER YOUR USERNAME FIRST';
     MESSAGE('BOSS PLEASE ENTER YOUR USERNAME FIRST');
     MESSAGE('BOSS PLEASE ENTER YOUR USERNAME FIRST');
  END IF;
  EXCEPTION
    WHEN OTHERS THEN
    :ERC_MES :='INVALID PASSWORD & USERNAME ';
    MESSAGE('INVALID PASSWORD & USERNAME');
    MESSAGE('INVALID PASSEPRD & USERNAME');
END;
/
  
  
  
  ------ END OF TEH PART OF MY LEARNING ABOUT ORACLE FORM INTERFACE -------
  
  