DESC DEPARTMENR;
CREATE TABLE DEPARTMENR(
  DEPARTMENR_ID NUMBER,
  DEPARTMENR_NAME VARCHAR2(30),
  MANAGER_ID NUMBER,
  LOCATON_ID NUMBER
);
INSERT INTO DEPARTMENR VALUES(101,'ICT',201,301);
INSERT INTO DEPARTMENR VALUES(102,'CSE',202,302);
INSERT INTO DEPARTMENR VALUES(103,'EEE',203,303);
INSERT INTO DEPARTMENR VALUES(104,'APECE',204,304);
INSERT INTO DEPARTMENR VALUES(105,'IIT',205,305);
SELECT * FROM DEPARTMENR;
DELETE FROM DEPARTMENR WHERE DEPARTMENR_ID = 105;

CREATE TABLE ORC_SOLUTION(
  S_ID NUMBER,
  O_NAME VARCHAR2(30),
  MGE_ID NUMBER,
  LOC_ID NUMBER
);
DESC ORC_SOLUTION;