CREATE TABLE STUDENT(
  CUS_ID NUMBER,
  F_NAME VARCHAR2(20),
  L_NAME VARCHAR2(20),
  DEPT varchar2(10),
  SALARY NUMBER,
  CITY varchar2(10)
);
DESC STUDENT;
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(1,'ALMAS','HOSSAIN','ICT',2000,'KUSHTIA');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(2,'MUJAHID','HOSSAIN','ICT',200000,'N-GONG');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(3,'kamrul','HOSSAIN','ICT',200000,'l-GONG');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES(4,'mohibur','HOSSAIN','cse',200000, 'k-GONG');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES (5,'UTSHO','HOSSAIN','BANGLA',100000,'DHAKA');
INSERT INTO STUDENT (CUS_ID,F_NAME,L_NAME,DEPT,SALARY,CITY)
VALUES (6,'SAMAR','ICT','MATH',50000,'SHAVAR');
SELECT * FROM STUDENT;


SET SERVEROUTPUT ON;

DECLARE 
  VAT VARCHAR2(100);
  V_SALARYT NUMBER;
BEGIN
  VAT := 'ALMAS HOSSAIN ANTAR';
  DBMS_OUTPUT.PUT_LINE(VAT);
  SELECT SALARY INTO V_SALARY FROM STUDENT
  WHERE CUS_ID=1;
END;

